import type { SourceId } from './character';

/** One verbatim SVG path from the basemap source, with its cumulative transform. */
export interface GeoPath {
  d: string;
  transform?: string;
}

/** Generated by scripts/build-basemap.ts — do not edit data/geo/basemap.json by hand. */
export interface BasemapData {
  attribution: { source: string; url: string; license: string };
  viewBox: string;
  /** lon/lat → map-unit calibration (plate-carrée source), for placing cities. */
  cal: { lonScale: number; lonOffset: number; latScale: number; latOffset: number };
  land: GeoPath[];
  foreign: GeoPath[];
  lakes: GeoPath[];
  coast: GeoPath[];
  regions: Record<string, GeoPath[]>;
  regionBounds: Record<string, { bbox: number[]; centroid: number[] }>;
  /** Authored patches for land the source assigns to no region; clipped to land. */
  regionExtensions?: Record<string, { points: number[][]; bbox: number[] }>;
  /** Authored sub-region polygons (map units), clipped to their parent at render time. */
  subregions?: Record<string, { points: number[][]; bbox: number[]; centroid: number[] }>;
}

/** Curated region metadata (data/geo/regions.json). `parent` nests sub-regions. */
export interface GeoRegion {
  id: string;
  name: string;
  greekName: string;
  parent: string | null;
  blurb: { text: string; sources: SourceId[] };
}

/** An ancient city (data/geo/cities.json); coordinates from Pleiades (CC BY). */
export interface GeoCity {
  id: string;
  name: string;
  greekName: string;
  region: string | null;
  coordinates: [number, number];
  pleiadesId: string;
}

/** One reign in a city's royal succession — a sourced, disputable fact. */
export interface Reign {
  ruler: string;
  characterId?: string;
  sources: SourceId[];
  citation?: string;
  note?: string;
  topic?: string;
}

export interface Lineage {
  city: string;
  reigns: Reign[];
}
