/** Generated by scripts/build-map-style.ts — public/geo/manifest.json */
export interface MapManifest {
  version: number;
  bounds: { west: number; south: number; east: number; north: number };
  maxBounds: [[number, number], [number, number]];
  center: [number, number];
  defaultZoom: number;
  minZoom: number;
  maxZoom: number;
  attribution: { name: string; url: string; license: string }[];
}
